"""Initial DB structure

Revision ID: 22d059a9f5f
Revises: None
Create Date: 2013-12-18 15:14:42.832658

"""

# revision identifiers, used by Alembic.
revision = '22d059a9f5f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('norm_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('state_info',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('keywords',
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('station_keywords',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['keyword'], ['keywords.text'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'keyword')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_keywords')
    op.drop_table('keywords')
    op.drop_table('state_info')
    op.drop_table('stations')
    ### end Alembic commands ###
